package com.sfa.persistence.sql;

public class NamedQuery {

	public static String QUOTE_QUERY = "Select Id, "
			+ "Name, "
			+ "CurrencyIsoCode, "
			+ "ReferenceNumber__c, "
			+ "Term__c, "
			+ "PricebookId__c, "
			+ "Number__c, "
			+ "IsCalculated__c, "
			+ "Type__c, "
			+ "StartDate__c, "
			+ "HasQuoteLineItems__c, "
			+ "Year1PaymentAmount__c, "
			+ "Year3PaymentAmount__c, "
			+ "Year2PaymentAmount__c, "
			+ "ExpirationDate__c, "
			+ "EffectiveDate__c, "
			+ "IsActive__c, "
			+ "Comments__c, "
			+ "Year5PaymentAmount__c, "
			+ "Version__c, "
			+ "Year6PaymentAmount__c, "
			+ "IsNonStandardPayment__c, "
			+ "Year4PaymentAmount__c, "
			+ "EndDate__c, "
			+ "Amount__c, "
			+ "PayNow__c, "
			+ "Status__c, "
			+ "LastCalculatedDate__c, "
			+ "LastPricedDate__c, "
			+ "QuoteOwnerId__r.Id, "
			+ "QuoteOwnerId__r.Name, "
			+ "QuoteOwnerId__r.Email, "
			+ "ContactId__r.Id, "
			+ "ContactId__r.Name, "
			+ "ContactId__r.Email, "			
			+ "CreatedDate, "
			+ "CreatedBy.Id, "
			+ "CreatedBy.Name, "
			+ "LastModifiedDate, "
			+ "LastModifiedBy.Id, "
			+ "LastModifiedBy.Name, "
			+ "OpportunityId__r.Id, "
			+ "OpportunityId__r.Name, "
			+ "OpportunityId__r.Description, " 
			+ "OpportunityId__r.StageName, " 
			+ "OpportunityId__r.Amount, " 
			+ "OpportunityId__r.Probability, "
			+ "OpportunityId__r.CloseDate, " 
			+ "OpportunityId__r.Type, " 
			+ "OpportunityId__r.IsClosed, " 
			+ "OpportunityId__r.IsWon, "
			+ "OpportunityId__r.ForecastCategory, " 
			+ "OpportunityId__r.CurrencyIsoCode, "
			+ "OpportunityId__r.HasOpportunityLineItem, " 
			+ "OpportunityId__r.CreatedDate, "
			+ "OpportunityId__r.LastModifiedDate, " 
			+ "OpportunityId__r.FulfillmentChannel__c, "
			+ "OpportunityId__r.OpportunityType__c, "
			+ "OpportunityId__r.PaymentType__c, "
			+ "OpportunityId__r.BillingAddress__c, " 
			+ "OpportunityId__r.ShippingAddress__c, "
			+ "OpportunityId__r.BillingCity__c, " 
			+ "OpportunityId__r.ShippingCity__c, " 
			+ "OpportunityId__r.BillingCountry__c, "
			+ "OpportunityId__r.ShippingCountry__c, " 
			+ "OpportunityId__r.BillingZipPostalCode__c, "
			+ "OpportunityId__r.ShippingZipPostalCode__c, " 
			+ "OpportunityId__r.BillingState__c, "
			+ "OpportunityId__r.ShippingState__c, " 
			+ "OpportunityId__r.OpportunityNumber__c,  "
			+ "OpportunityId__r.Pay_Now__c, " 
			+ "OpportunityId__r.Country_of_Order__c, " 
			+ "OpportunityId__r.Super_Region__c, "        
			+ "OpportunityId__r.Account.Id, "
            + "OpportunityId__r.Account.BillingCity, "
            + "OpportunityId__r.Account.BillingCountry, "
            + "OpportunityId__r.Account.BillingPostalCode, " 
            + "OpportunityId__r.Account.BillingState, "
            + "OpportunityId__r.Account.BillingStreet, "
            + "OpportunityId__r.Account.ShippingCity, "
            + "OpportunityId__r.Account.ShippingCountry, "
            + "OpportunityId__r.Account.ShippingPostalCode, "
            + "OpportunityId__r.Account.ShippingState, "
            + "OpportunityId__r.Account.ShippingStreet, "
            + "OpportunityId__r.Account.VATNumber__c, "  			
			+ "OpportunityId__r.Account.Name, "
			+ "OpportunityId__r.Account.OracleAccountNumber__c, "
			+ "OpportunityId__r.Account.Account_Alias_Name__c, " 
			+ "OpportunityId__r.Owner.Id, "
			+ "OpportunityId__r.Owner.Name, "
			+ "OpportunityId__r.Owner.FirstName, " 
			+ "OpportunityId__r.Owner.LastName, " 
			+ "OpportunityId__r.Owner.ContactId, "
			+ "OpportunityId__r.Owner.Email, " 
			+ "OpportunityId__r.Owner.Phone, " 
			+ "OpportunityId__r.Owner.Title, "
			+ "OpportunityId__r.Owner.Department, " 
			+ "OpportunityId__r.Owner.UserRole.Name, "
			+ "OpportunityId__r.Owner.Profile.Name, " 
			+ "OpportunityId__r.CreatedBy.Id, " 
			+ "OpportunityId__r.CreatedBy.Name, "
			+ "OpportunityId__r.CreatedBy.FirstName, " 
			+ "OpportunityId__r.CreatedBy.LastName, "
			+ "OpportunityId__r.LastModifiedBy.Id, " 
			+ "OpportunityId__r.LastModifiedBy.Name, "
			+ "OpportunityId__r.LastModifiedBy.FirstName, " 
			+ "OpportunityId__r.LastModifiedBy.LastName, "
			+ "OpportunityId__r.Pricebook2.Id, " 
			+ "OpportunityId__r.Pricebook2.Name, " 
			+ "(Select Id, "
			+ "        Name, "
			+ "        CurrencyIsoCode, "
			+ "        CreatedDate, "
			+ "        CreatedBy.Id, "
			+ "        CreatedBy.Name, "
			+ "        LastModifiedDate, "
			+ "        LastModifiedBy.Id, "
			+ "        LastModifiedBy.Name, "
			+ "        OpportunityLineItemId__c, "
			+ "        Quantity__c, "
			+ "        EndDate__c, "
			+ "        ContractNumbers__c, "
			+ "        ListPrice__c, "
			+ "        OpportunityId__c, "
			+ "        Term__c, "
			+ "        UnitPrice__c, "
			+ "        LineNumber__c, "
			+ "        YearlySalesPrice__c, "
			+ "        NewOrRenewal__c, "
			+ "        QuoteId__c, "
			+ "        DiscountAmount__c, "
			+ "        DiscountPercent__c, "
			+ "        Product__r.Id, "
			+ "        Product__r.Description, "
			+ "        Product__r.Name, "
			+ "        Product__r.Family, "
			+ "        Product__r.ProductCode, "
			+ "        Product__r.Primary_Business_Unit__c, "
			+ "        Product__r.Product_Line__c, "
			+ "        Product__r.Unit_Of_Measure__c, "
			+ "        Product__r.Term__c, "
			+ "        TotalPrice__c, "
			+ "        StartDate__c, "
			+ "        PricebookEntryId__c, "
			+ "        Configured_SKU__c, "
			+ "        ProductDescription__c, "
			+ "        Pricing_Attributes__c, "
			+ "        Code__c, "
			+ "        Message__c "
			+ " From   QuoteLineItem__r "
			+ "Order By LineNumber__c, CreatedDate), "
			+ "(Select Id, "
			+ "        QuoteId__c, "
			+ "        Amount__c, "
			+ "        Percent__c, "
			+ "        Reason__c, "
			+ "        Type__c, "
			+ "        AppliesTo__c, "
			+ "        Operator__c "
			+ " From   QuotePriceAdjustment__r "
			+ "Order By Reason__c), "
			+ "(Select Id, "
			+ "        Name, "
			+ "        CurrencyIsoCode, "
			+ "        CreatedDate, "
			+ "        CreatedById, "
			+ "        LastModifiedDate, "
			+ "        LastModifiedById, "
			+ "        ProrateUnitPrice__c, "
			+ "        Type__c, "
			+ "        ProrateTotalPrice__c, "
			+ "        ProrateYearTotalPrice__c, "
			+ "        QuoteId__c, "
			+ "        StartDate__c, "
			+ "        PricePerDay__c, "
			+ "        Year__c, "
			+ "        EndDate__c, "
			+ "        ProrateYearUnitPrice__c, "
			+ "        QuoteLineItemId__r.Id, "
			+ "        QuoteLineItemId__r.ProductDescription__c, "
			+ "        QuoteLineItemId__r.Product__r.Id, "
			+ "        QuoteLineItemId__r.Product__r.Description, "
			+ "        QuoteLineItemId__r.Product__r.Name, "
			+ "        QuoteLineItemId__r.Product__r.Family, "
			+ "        QuoteLineItemId__r.Product__r.ProductCode, "
			+ "        QuoteLineItemId__r.Product__r.Primary_Business_Unit__c, "
			+ "        QuoteLineItemId__r.Product__r.Product_Line__c, "
			+ "        QuoteLineItemId__r.Product__r.Unit_Of_Measure__c, "
			+ "        QuoteLineItemId__r.Product__r.Term__c, "
			+ "        QuoteLineItemId__r.StartDate__c, "
			+ "        QuoteLineItemId__r.EndDate__c, "
			+ "        QuoteLineItemId__r.Term__c, "
			+ "        QuoteLineItemId__r.Quantity__c, "
			+ "        QuoteLineItemId__r.YearlySalesPrice__c, "
			+ "        QuoteLineItemId__r.TotalPrice__c, "
			+ "        QuoteLineItemId__r.ContractNumbers__c "
			+ "From   QuoteLineItemSchedule__r "
			+ "Order  By EndDate__c, QuoteLineItemId__r.Product__r.ProductCode) "
			+ "From   Quote__c ";
	
}